name: tig

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.6+10

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Routing Service
  go_router: ^16.2.0
  # Admob
  google_mobile_ads: ^5.1.0
  # Environment Variables
  flutter_dotenv: ^5.1.0
  # Code Generation
  build_runner: ^2.4.6
  json_serializable: ^6.6.2
  # localization
  intl: ^0.20.2
  intl_utils: ^2.8.9
  # Firebase
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  # Social Login
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2
  # State Management
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  # Local Database
  shared_preferences: ^2.3.2
  # Email Sender
  flutter_email_sender: ^6.0.3
  # Android Home Widget
  home_widget: ^0.7.0
  # Dependency Injection
  get_it: ^8.0.2
  equatable: ^2.0.5
  # Others
  flutter_keyboard_visibility: ^6.0.0
  kakao_flutter_sdk_user: ^1.9.5
  flutter_native_splash: ^2.4.2
  just_audio: ^0.9.42

flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#FFFFFF"
  color_dark: "#000000"
  image: "assets/images/dark_logo.png"
  image_dark: "assets/images/light_logo.png"
  android_12:
    color: "#FFFFFF"
    color_dark: "#000000"
    image: "assets/images/dark_logo.png"
    image_dark: "assets/images/light_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/sounds/
    - assets/images/
    - assets/images/login_button/
  fonts:
    - family: CangJiGaoDeGuoMiaoHei
      fonts:
        - asset: assets/fonts/CangJiGaoDeGuoMiaoHei.ttf
    - family: MaoKenShiJinHei
      fonts:
        - asset: assets/fonts/MaoKenShiJinHei.ttf
    - family: PaperlogyRegular
      fonts:
        - asset: assets/fonts/Paperlogy-Regular.ttf
    - family: PaperlogySemiBold
      fonts:
        - asset: assets/fonts/Paperlogy-SemiBold.ttf
    - family: PaperlogyExtraBold
      fonts:
        - asset: assets/fonts/Paperlogy-ExtraBold.ttf
    - family: NanumBrush
      fonts:
        - asset: assets/fonts/NanumBrush.ttf
    - family: ShigotoMemogaki
      fonts:
        - asset: assets/fonts/ShigotoMemogaki.ttf