name: tig
description: "A new Flutter project."

<<<<<<< HEAD
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+3
=======
version: 1.0.0+1
>>>>>>> aeab220 (feat: use adapty to manage in-app-purchase)

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_mobile_ads: ^5.1.0
  flutter_dotenv: ^5.1.0
  build_runner: ^2.4.6
  intl: ^0.19.0
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2
  cloud_firestore: ^5.4.1
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  flutter_email_sender: ^6.0.3
  home_widget: ^0.7.0
  flutter_keyboard_visibility: ^6.0.0
  kakao_flutter_sdk_user: ^1.9.5
  flutter_native_splash: ^2.4.2
  adapty_flutter: ^2.10.3

flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#FFFFFF"
  color_dark: "#000000"
  image: "assets/images/dark_logo.png"
  image_dark: "assets/images/light_logo.png"
  android_12:
    color: "#FFFFFF"
    color_dark: "#000000"
    image: "assets/images/dark_logo.png"
    image_dark: "assets/images/light_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/login_button/
  fonts:
    - family: CangJiGaoDeGuoMiaoHei
      fonts:
        - asset: assets/fonts/CangJiGaoDeGuoMiaoHei.ttf
    - family: MaoKenShiJinHei
      fonts:
        - asset: assets/fonts/MaoKenShiJinHei.ttf
    - family: PaperlogyRegular
      fonts:
        - asset: assets/fonts/Paperlogy-Regular.ttf
    - family: PaperlogySemiBold
      fonts:
        - asset: assets/fonts/Paperlogy-SemiBold.ttf
    - family: PaperlogyExtraBold
      fonts:
        - asset: assets/fonts/Paperlogy-ExtraBold.ttf
    - family: NanumBrush
      fonts:
        - asset: assets/fonts/NanumBrush.ttf
    - family: ShigotoMemogaki
      fonts:
        - asset: assets/fonts/ShigotoMemogaki.ttf

dart_obfuscate: true